README.md

Added the section clicker into a browser games, and added two games

---

README.md

Feel free to thoroughly review my changes

Added a couple of more games, mostly browser based

---

README.md

add 0hh1 and 2048

---

README.md

added 2 games (battle for wesnoth and 0.a.d) as well as Allegro 5 engine

added 2 games and 1 engine

---

README.md

Hey! [Reddit brought me here](http://www.reddit.com/r/learnprogramming/comments/2tlan2/list_of_75_open_source_games_on_github/).
I added [```Pygame```](https://www.pygame.org/) and [```Pyglet```](https://www.pyglet.org/) [```Python```](https://www.python.org/) libraries for writing games, along with Minecraft-inspired demo created in ```Python``` and ```Pyglet```, as well as [```OGRE```](http://www.ogre3d.org/) - an open source 3D graphics engine.
Cheers!

Python games

---

README.md

Hi.
I have sorted the items in some sections.
Regards.

Sort the items

---

README.md

Hey! :v: 
I added 4 game engines found in the [Game Engines Showcase](https://github.com/showcases/game-engines)(other game engines found in that showcase are already in this repo), as well as 2 other game engines that were mentioned in repo, but not linked under ```Engines``` section([```Flare```](https://github.com/jhgrng/games/commit/086108db330057d91f29e16615502988bbb9c18f) and [```LÖVE```](https://github.com/jhgrng/games/commit/7d2e08b0269457069db3f1dcc015e1f446acfb99)).

Game Engines

---

README.md

Hey! :hand: 
I reviewed [GitHub Game Off Winners Showcase](https://github.com/showcases/game-off-winners) and spotted a few games that weren't on this list, so I decided to add them.

Game Off Winners

---

README.md

Hey! :wave: 
I was exploring [GitHub JavaScript Game Engines Showcase](https://github.com/showcases/javascript-game-engines) and added a few that weren't listed here.

JavaScript Engines

---

README.md

Hello!
I found some JS games and thought I'd put them here :)

JavaScript Games

---

README.md

@leereilly Please take a look.

Add Greenworks.

---

README.md

Captain Rogers link update

---

README.md

These are two browser-based puzzle games I made for jams. They are feature-complete and contain many levels, so contain more play time than your average jam game.
Both made in [phaser](https://github.com/photonstorm/phaser), which is also on Github :+1:

Add browser puzzle games Beatrix, Drunken Viking

---

README.md

Hey,
I spotted that 3 weeks ago a [Pull Request was opened](https://github.com/leereilly/games/pull/84) but there was no action due to a merge conflict, so I decided to fix it. 2 simple typos, hope @Casmo doesn't mind :)

Resolved #84

---

README.md

add ZK to strategies list.

---

README.md

binb has moved to [https://binb.co](https://binb.co).

Fix binb url

---

README.md

Hey,
Resolved issues [#106](https://github.com/leereilly/games/issues/106) and [#107](https://github.com/leereilly/games/issues/107).

Unresolved issues

---

README.md

Open source MMORPG. There are two versions with their own codebases and servers.

Added Meridian 59 under MMORPG section.

---

README.md

Freeciv-web is an Open Source strategy game implemented in HTML5, which can be played online against other players, or in single player mode against AI opponents.

Add freeciv-web

---

README.md

EaselJS moved to new repository

EaselJS moved to new repository

---

README.md

Fixing link typo in JiGS

---

README.md

Space Engineers is a voxel-based sandbox game set in an asteroid field in space.

Add Space Engineers

---

README.md

Add game StarCraft into Strategy

---

README.md

Hey,
I stumbled upon GemRB, a portable open-source implementation of Bioware's Infinity Engine. Thought that's pretty awesome and since it's hosted on GitHub, I decided to add it. :)
Besides that I resolved some unresolved issues, hope that helps.

Added 'GemRB' to Engines section

---

README.md

Location and name of this repository changed.

Update link to Open Meridian repository.

---

README.md

Breakout multiplayer built in javascript

Breakout multiplayer

---

README.md

Tiled map editor

---

README.md

This adds the puzzle game [cube-composer](https://github.com/sharkdp/cube-composer) to the web section (Disclaimer: I'm the author :smile:).

Add cube-composer

---

README.md

Added OpenTTD fixing #156

---

README.md

It's renewed version of old ping pong game

Added Cyber Pong

---

README.md

GPLv3 licensed soft body physics simulator. Main page: www.rigsofrods.com

Add Rigs of Rods

---

README.md

because it's a fun local multiplayer game! Take a look at it https://github.com/amiruqdah/mario-party

added HFT Mario Party

---

README.md

Witch Blast is a free 2D action game with random dungeon and stuff, similar to The Binding of Isaac.
In GameJolt: http://gamejolt.com/games/witch-blast/95627
Trailer: https://www.youtube.com/watch?v=FsHqu0JpP_k

ADD game Witch Blast

---

README.md

From Browser > FPS, we aren't web yet ;)
Maybe one day, in the far future, we'll try to be GLES2.0-compliant and compiled using Emscripten... But that's another story.

Move glPortal to Native > FPS

---

README.md

Awesome repo! I'd like to add my Ceros Snake game.

Add Ceros Snake

---

README.md

Stendhal is a fun friendly and free 2D multiplayer online adventure game with an old school feel.

added Stendhal

---

README.md

This PR addresses #181, by adding the game in a new category for native games.

Add OpenNotrium

---

README.md

Project Cube

---

README.md

Flappy Bird added to arcade games

Flappy Bird added to arcade games

---

README.md

Hi, this is my game created with PhaserJs, please add this game in Arcade section.

Add "jolly jumper" in arcade.

---

README.md

Added link to XLE, a MIT license game rendering engine on github.

Added link to XLE game rendering engine

---

README.md

came across this nice little game among the demos of the d3 library ( https://github.com/mbostock/d3/wiki/Gallery )

add d3shooter

---

README.md

[heXon](https://luckeyproductions.itch.io/hexon) is a FOSS twin-stick-shooter by [LucKey Productions](https://luckeyproductions.itch.io/) created using the [Urho3D](http://urho3d.github.io/) game engine.

Added heXon to the list

---

README.md

Sakura Fly is an iOS game available on App Store

Add Sakura Fly by @l800891

---

README.md

Space shooter is a 2-D, cross platform game which can run on
- linux
- windows
- MAC 
based systems.

Added prodicus/spaceShooter

---

README.md

I’ve added my little platformer to the list.

Added Captain Holetooth

---

README.md

I'd also like to split off all shooter games of "Arcade" because that category is getting quite busy.
If that's okay with you I can take care of it.

Add JumpSuit

---

README.md

WPilot, a browser based space game in NodeJS & HTML5

Add WPilot

---

README.md

Added three of my games. Thanks!

Kriegspiel, Anagramica, Shape Experiment

---

README.md

Add Chat bot category, and add [c4bot](https://github.com/kenrick95/c4bot).

Add Chat bot category, and add c4bot

---

README.md

[Play store link](https://play.google.com/store/apps/details?id=com.prakharme.prakharsriv.colorphun)

Added Colorphun

---

README.md

Adds native [Missile Command](https://github.com/chadpaulson/missile-command) clone written in Lua with [LÖVE](http://love2d.org/).

Add Missile Command

---

README.md

Added freeablo, open source Diablo I engine implementation (https://github.com/wheybags/freeablo) to the native RPG section.

Add freeablo

---

README.md

Fix link to Roguish

---

README.md

It was linked to a fork, which is is out of date.

changed A Dark Room url to original repo

---

README.md

https://github.com/leereilly/games/issues/272

Added OpenRTS

---

README.md

Canvas based HTML5 game where a player has to extinguish fire on trees using his magical water tank in order to save the Burning Forest.

Added save the forest arcade game.

---

README.md

Just a lil' puzzle I wrote for the JS13K compo earlier this year.

Add Couch 2048

---

README.md

...spotted on hackernews today

add OpenLara

---

README.md

Open Fodder moved to its own org

Update link for Open Fodder

---

README.md

2D platform game created with home made game engine using OpenGL + SDL (Simple DirectMedia Layer) for Computer Science project.

Add Sky Engine

---

README.md

Add Hexa Battle, A turn based dungeon crawler written with Typescript, using React and SVG.

Add Hexa-Battle

---

README.md

https://github.com/FreezingMoon/AncientBeast

added AncientBeast.com

---

README.md

A better version of the classic.

Added new Snake game.

---

README.md

Add to
- 3D Hartwing Chess Set
- Cube Engine
- Project Cube

Add "Play it now!" to some games

---

README.md

Just thought it'd feel right at home on that list!

🐿 Add itch to utilities

---

README.md

I have created a subtitle '[programming game](https://en.wikipedia.org/wiki/Programming_game)'.

cengball programming game added.

---

README.md

fix the play link of the TransCube

---

README.md

fix the play link of Orbium

---

README.md

Puzzle game built using JavaScript.

Add Hexahedral

---

README.md

Added Hedgewars to Native Strategy Games per issue #256

---

README.md

changed coffee script to coffeescript

minor README.MD changes

---

README.md

- An open-source Tomb Raider 1-5 engine remake http://opentomb.github.io/

Added OpenTomb

---

README.md

Add "Cendric"

---

README.md

This adds my game, BlicblockJS, to the Puzzle section of browser games.

Add BlicblockJS to browser-based puzzle games section

---

README.md

Browser-based puzzle: Add Hex 2048

---

README.md

Removed extra space that breaks markdown link rendering

Fixed OpenDungeons link
